// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {},
    "definitions": {
        "controller.FailureResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "controller.SuccessResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "model.Attribute": {
            "type": "object",
            "properties": {
                "attributeId": {
                    "type": "integer"
                },
                "attributeValueId": {
                    "type": "integer"
                },
                "customAttributeValue": {
                    "type": "string"
                }
            }
        },
        "model.DeliveryOption": {
            "type": "object",
            "properties": {
                "deliveryDuration": {
                    "type": "integer"
                },
                "fastDeliveryType": {
                    "type": "string"
                }
            }
        },
        "model.Image": {
            "type": "object",
            "properties": {
                "url": {
                    "type": "string"
                }
            }
        },
        "model.Product": {
            "type": "object",
            "properties": {
                "attributes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Attribute"
                    }
                },
                "barcode": {
                    "type": "string"
                },
                "brandId": {
                    "type": "integer"
                },
                "cargoCompanyId": {
                    "type": "integer"
                },
                "categoryId": {
                    "type": "integer"
                },
                "currencyType": {
                    "type": "string"
                },
                "deliveryOption": {
                    "$ref": "#/definitions/model.DeliveryOption"
                },
                "description": {
                    "type": "string"
                },
                "dimensionalWeight": {
                    "type": "integer"
                },
                "images": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Image"
                    }
                },
                "listPrice": {
                    "type": "number"
                },
                "productMainId": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                },
                "salePrice": {
                    "type": "number"
                },
                "stockCode": {
                    "type": "string"
                },
                "suplierId": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "vatRate": {
                    "type": "integer"
                }
            }
        },
        "model.ProductsResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Product"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer"
                },
                "totalElements": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
