definitions:
  controller.FailureResponse:
    properties:
      error:
        type: string
      message:
        type: string
    type: object
  controller.SuccessResponse:
    properties:
      data: {}
      message:
        type: string
    type: object
  model.Attribute:
    properties:
      attributeId:
        type: integer
      attributeValueId:
        type: integer
      customAttributeValue:
        type: string
    type: object
  model.DeliveryOption:
    properties:
      deliveryDuration:
        type: integer
      fastDeliveryType:
        type: string
    type: object
  model.Image:
    properties:
      url:
        type: string
    type: object
  model.Product:
    properties:
      attributes:
        items:
          $ref: '#/definitions/model.Attribute'
        type: array
      barcode:
        type: string
      brandId:
        type: integer
      cargoCompanyId:
        type: integer
      categoryId:
        type: integer
      currencyType:
        type: string
      deliveryOption:
        $ref: '#/definitions/model.DeliveryOption'
      description:
        type: string
      dimensionalWeight:
        type: integer
      images:
        items:
          $ref: '#/definitions/model.Image'
        type: array
      listPrice:
        type: number
      productMainId:
        type: string
      quantity:
        type: integer
      salePrice:
        type: number
      stockCode:
        type: string
      supplierId:
        type: integer
      title:
        type: string
      vatRate:
        type: integer
    type: object
info:
  contact: {}
paths:
  /products:
    get:
      consumes:
      - application/json
      description: Retrieves a list of products from the supplier API and returns
        it
      parameters:
      - description: SuplierID
        in: path
        name: suplier_id
        required: true
        type: string
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Page size
        in: query
        name: size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: List of namespaces
          schema:
            $ref: '#/definitions/controller.SuccessResponse'
        "500":
          description: Bad request or error message
          schema:
            $ref: '#/definitions/controller.FailureResponse'
      summary: Retrieve a list of products from the supplier API
      tags:
      - products
  /products/{id}:
    get:
      consumes:
      - application/json
      description: Retrieves a product from the supplier API and returns it
      parameters:
      - description: ProductMainID
        in: path
        name: id
        required: true
        type: string
      - description: SuplierID
        in: path
        name: suplier_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.Product'
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.FailureResponse'
      summary: Retrieve a product by Product Main ID
      tags:
      - products
swagger: "2.0"
